<?PHP 
$CONFIGURATION=1;

// CODE NON PARAMETRABLE
global $DOCUMENTS_IMG_LOGO;
$EXTRAIT_COMPTE['IMG_LOGO']	= $DOCUMENTS_IMG_LOGO;

$EXTRAIT_COMPTE['HAUTEUR_LINE_FACTURE']			= 5;
$EXTRAIT_COMPTE['HAUTEUR_LINE_TOTAUX_GENERAUX']		= 5;
$EXTRAIT_COMPTE['HAUTEUR_LINE_VIDE']				= 5;


$EXTRAIT_COMPTE['ENTETE_COL_REF'] = "Référence";
$EXTRAIT_COMPTE['ENTETE_COL_CLIENT'] = "Client";
$EXTRAIT_COMPTE['ENTETE_COL_CREATION'] = "Création";
$EXTRAIT_COMPTE['ENTETE_COL_ECHEANCE']  = "Echéance";
$EXTRAIT_COMPTE['ENTETE_COL_RELANCE']  = "Relance";
$EXTRAIT_COMPTE['ENTETE_COL_MONTANT'] 	= "Restant dû";
$EXTRAIT_COMPTE['ENTETE_COL_MAGASIN'] 	= "Mag";

$EXTRAIT_COMPTE['LARGEUR_COL_REF'] = 35;
$EXTRAIT_COMPTE['LARGEUR_COL_CLIENT'] = 60;
$EXTRAIT_COMPTE['LARGEUR_COL_CREATION'] = 20;
$EXTRAIT_COMPTE['LARGEUR_COL_ECHEANCE'] = 20;
$EXTRAIT_COMPTE['LARGEUR_COL_RELANCE'] = 20;
$EXTRAIT_COMPTE['LARGEUR_COL_MONTANT'] = 20;
$EXTRAIT_COMPTE['LARGEUR_COL_MAGASIN'] = 15;

// ***************************************************
// POSITION DES BLOCS
$EXTRAIT_COMPTE['MARGE_GAUCHE'] = 10;
$EXTRAIT_COMPTE['MARGE_HAUT']		= 10;

// CORPS DU DOCUMENT
$EXTRAIT_COMPTE['CORPS_HAUTEUR_DEPART']	= 45;
$EXTRAIT_COMPTE['CORPS_HAUTEUR_MAX']		= 205;

// PIEDS DE PAGE
$EXTRAIT_COMPTE['PIEDS_HAUTEUR_DEPART']	= 260;
$EXTRAIT_COMPTE['PIEDS_HAUTEUR_MAX']		= 12;

// ***************************************************
// TEXTES ENTRE CORPS ET PIEDS DE PAGE
$ETAT_STOCK['TEXTE_CORPS_PIEDS'][0]	= "";

// ***************************************************
// TEXTES DE PIEDS DE PAGE
global $PIED_DE_PAGE_GAUCHE_0;
global $PIED_DE_PAGE_GAUCHE_1;
global $PIED_DE_PAGE_DROIT_0;
global $PIED_DE_PAGE_DROIT_1;
$EXTRAIT_COMPTE['PIEDS_GAUCHE'][0]	= $PIED_DE_PAGE_GAUCHE_0;
$EXTRAIT_COMPTE['PIEDS_GAUCHE'][1]	= $PIED_DE_PAGE_GAUCHE_1;
$EXTRAIT_COMPTE['PIEDS_DROIT'][0]	= $PIED_DE_PAGE_DROIT_0;
$EXTRAIT_COMPTE['PIEDS_DROIT'][1]	= $PIED_DE_PAGE_DROIT_1;



//variable//type de champ(parametre)//libéllé//commentaire
// PARAMETRES MODIFIABLES
// FIN PARAMETRES MODIFIABLES
// CONFIGURATION PAR DEFAUT
// Portion de code recopiée dans la partie « paramètres modifiables » en cas de remise à 0 des paramètres.
/*
*/
// FIN CONFIGURATION PAR DEFAUT
// INFORMATIONS SUR L’AUTEUR
/* 
*/
?>