<?PHP 
$CONFIGURATION=1;

// CODE NON PARAMETRABLE
global $DOCUMENTS_IMG_LOGO;
$JOURNAUX['IMG_LOGO']	= $DOCUMENTS_IMG_LOGO;

$JOURNAUX['HAUTEUR_LINE_ARTICLE']			= 5;
$JOURNAUX['HAUTEUR_LINE_CATEGORIE']		= 5;
$JOURNAUX['HAUTEUR_LINE_TOTAUX_CATEGORIE']		= 5;
$JOURNAUX['HAUTEUR_LINE_TOTAUX_GENERAUX']		= 5;
$JOURNAUX['HAUTEUR_LINE_VIDE']				= 5;

$JOURNAUX['HAUTEUR_AFTER_LINE_ARTICLE']			= 0;
$JOURNAUX['HAUTEUR_AFTER_LINE_CATEGORIE']		= 0;
$JOURNAUX['HAUTEUR_AFTER_LINE_TOTAUX_CATEGORIE']		= 0;

$JOURNAUX['ENTETE_COL_DAT'] = "Date";
$JOURNAUX['ENTETE_COL_REF'] = "N° pièce / Réf Doc";
$JOURNAUX['ENTETE_COL_TTC'] = "";
$JOURNAUX['ENTETE_COL_COM'] = "Tiers";
$JOURNAUX['ENTETE_COL_LIB'] = "Libellé";
$JOURNAUX['ENTETE_COL_CMT'] = "N° de compte";
$JOURNAUX['ENTETE_COL_P']  = "";

$JOURNAUX['LARGEUR_COL_DAT'] = 19;
$JOURNAUX['LARGEUR_COL_REF'] = 30;
$JOURNAUX['LARGEUR_COL_TTC'] = 21;
$JOURNAUX['LARGEUR_COL_COM'] = 39;
$JOURNAUX['LARGEUR_COL_LIB'] = 39;
$JOURNAUX['LARGEUR_COL_CMT'] = 21;
$JOURNAUX['LARGEUR_COL_P'] = 21;

// ***************************************************
// POSITION DES BLOCS
$JOURNAUX['MARGE_GAUCHE'] = 10;
$JOURNAUX['MARGE_HAUT']		= 10;

// CORPS DU DOCUMENT
$JOURNAUX['CORPS_HAUTEUR_DEPART']	= 45;
$JOURNAUX['CORPS_HAUTEUR_MAX']		= 205;

// PIEDS DE PAGE
$JOURNAUX['PIEDS_HAUTEUR_DEPART']	= 260;
$JOURNAUX['PIEDS_HAUTEUR_MAX']		= 12;

// ***************************************************
// TEXTES ENTRE CORPS ET PIEDS DE PAGE
$JOURNAUX['TEXTE_CORPS_PIEDS'][0]	= "";

// ***************************************************
// TEXTES DE PIEDS DE PAGE
global $PIED_DE_PAGE_GAUCHE_0;
global $PIED_DE_PAGE_GAUCHE_1;
global $PIED_DE_PAGE_DROIT_0;
global $PIED_DE_PAGE_DROIT_1;
$JOURNAUX['PIEDS_GAUCHE'][0]	= $PIED_DE_PAGE_GAUCHE_0;
$JOURNAUX['PIEDS_GAUCHE'][1]	= $PIED_DE_PAGE_GAUCHE_1;
$JOURNAUX['PIEDS_DROIT'][0]	= $PIED_DE_PAGE_DROIT_0;
$JOURNAUX['PIEDS_DROIT'][1]	= $PIED_DE_PAGE_DROIT_1;



//variable//type de champ(parametre)//libéllé//commentaire
// PARAMETRES MODIFIABLES
// FIN PARAMETRES MODIFIABLES
// CONFIGURATION PAR DEFAUT
// Portion de code recopiée dans la partie « paramètres modifiables » en cas de remise à 0 des paramètres.
/*
*/
// FIN CONFIGURATION PAR DEFAUT
// INFORMATIONS SUR L’AUTEUR
/* 
*/
?>