<?PHP 
$CONFIGURATION=1;

// CODE NON PARAMETRABLE
global $DOCUMENTS_IMG_LOGO;
$RELEVE_COMPTE['IMG_LOGO']	= $DOCUMENTS_IMG_LOGO;

$RELEVE_COMPTE['HAUTEUR_LINE_FACTURE']			= 5;
$RELEVE_COMPTE['HAUTEUR_LINE_TOTAUX_GENERAUX']		= 5;
$RELEVE_COMPTE['HAUTEUR_LINE_VIDE']				= 5;

$RELEVE_COMPTE['ENTETE_COL_DATE'] = "Date";
$RELEVE_COMPTE['ENTETE_COL_LIBELLE'] = "Libellé";
$RELEVE_COMPTE['ENTETE_COL_CREDIT'] = "Crédit";
$RELEVE_COMPTE['ENTETE_COL_DEBIT']  = "Débit";
$RELEVE_COMPTE['ENTETE_COL_SOLDE']  = "Solde";
$RELEVE_COMPTE['ENTETE_COL_REPORT'] 	= "Report";

$RELEVE_COMPTE['LARGEUR_COL_DATE'] = 35;
$RELEVE_COMPTE['LARGEUR_COL_LIBELLE'] = 95;
$RELEVE_COMPTE['LARGEUR_COL_CREDIT'] = 20;
$RELEVE_COMPTE['LARGEUR_COL_DEBIT'] = 20;
$RELEVE_COMPTE['LARGEUR_COL_SOLDE'] = 20;

// ***************************************************
// POSITION DES BLOCS
$RELEVE_COMPTE['MARGE_GAUCHE'] = 10;
$RELEVE_COMPTE['MARGE_HAUT']		= 10;

// CORPS DU DOCUMENT
$RELEVE_COMPTE['CORPS_HAUTEUR_DEPART']	= 30;
$RELEVE_COMPTE['CORPS_HAUTEUR_MAX']		= 220;

// PIEDS DE PAGE
$RELEVE_COMPTE['PIEDS_HAUTEUR_DEPART']	= 260;
$RELEVE_COMPTE['PIEDS_HAUTEUR_MAX']		= 12;

// ***************************************************
// TEXTES ENTRE CORPS ET PIEDS DE PAGE
$ETAT_STOCK['TEXTE_CORPS_PIEDS'][0]	= "";

// ***************************************************
// TEXTES DE PIEDS DE PAGE
global $PIED_DE_PAGE_GAUCHE_0;
global $PIED_DE_PAGE_GAUCHE_1;
global $PIED_DE_PAGE_DROIT_0;
global $PIED_DE_PAGE_DROIT_1;
$RELEVE_COMPTE['PIEDS_GAUCHE'][0]	= $PIED_DE_PAGE_GAUCHE_0;
$RELEVE_COMPTE['PIEDS_GAUCHE'][1]	= $PIED_DE_PAGE_GAUCHE_1;
$RELEVE_COMPTE['PIEDS_DROIT'][0]	= $PIED_DE_PAGE_DROIT_0;
$RELEVE_COMPTE['PIEDS_DROIT'][1]	= $PIED_DE_PAGE_DROIT_1;



//variable//type de champ(parametre)//libéllé//commentaire
// PARAMETRES MODIFIABLES
// FIN PARAMETRES MODIFIABLES
// CONFIGURATION PAR DEFAUT
// Portion de code recopiée dans la partie « paramètres modifiables » en cas de remise à 0 des paramètres.
/*
*/
// FIN CONFIGURATION PAR DEFAUT
// INFORMATIONS SUR L’AUTEUR
/* 
*/
?>