<?php 
$CONFIGURATION=0;
$STAT_STANDARD['X'] = 0;

$STAT_STANDARD['HAUTEUR_FEUILLE'] = 210;
$STAT_STANDARD['MARGE_BAS'] = 10;

$STAT_STANDARD['LARGEUR_CELL_LIB'] = 42;
$STAT_STANDARD['LARGEUR_CELL_MOIS'] = 17;
$STAT_STANDARD['LARGEUR_CELL_TOTAL'] = 17;

?>