<?PHP 
$CONFIGURATION=1;

// CODE NON PARAMETRABLE
global $DOCUMENTS_IMG_LOGO;
$ETAT_STOCK['IMG_LOGO']	= $DOCUMENTS_IMG_LOGO;

$ETAT_STOCK['HAUTEUR_LINE_ARTICLE']				= 5;
$ETAT_STOCK['HAUTEUR_LINE_CATEGORIE']			= 5;
$ETAT_STOCK['HAUTEUR_LINE_TOTAUX_CATEGORIE']	= 5;
$ETAT_STOCK['HAUTEUR_LINE_TOTAUX_GENERAUX']		= 5;
$ETAT_STOCK['HAUTEUR_LINE_VIDE']				= 5;
$ETAT_STOCK['HAUTEUR_LINE_SN']					= 4;

$ETAT_STOCK['HAUTEUR_AFTER_LINE_ARTICLE']			= 0;
$ETAT_STOCK['HAUTEUR_AFTER_LINE_CATEGORIE']			= 0;
$ETAT_STOCK['HAUTEUR_AFTER_LINE_TOTAUX_CATEGORIE']	= 0;

$ETAT_STOCK['ENTETE_COL_REF'] = "Référence";
$ETAT_STOCK['ENTETE_COL_DES'] = "Désignation";
$ETAT_STOCK['ENTETE_COL_QTE'] = "Qté";
$ETAT_STOCK['ENTETE_COL_PU']  = "PU HT";
$ETAT_STOCK['ENTETE_COL_PT'] 	= "PT HT";

$ETAT_STOCK['LARGEUR_COL_REF'] = 30;
$ETAT_STOCK['LARGEUR_COL_LIB'] = 95;
$ETAT_STOCK['LARGEUR_COL_QTE'] = 10;
$ETAT_STOCK['LARGEUR_COL_PU'] = 20;
$ETAT_STOCK['LARGEUR_COL_PT'] = 25;

// ***************************************************
// POSITION DES BLOCS
$ETAT_STOCK['MARGE_GAUCHE'] = 15;
$ETAT_STOCK['MARGE_HAUT']		= 15;

// CORPS DU DOCUMENT
$ETAT_STOCK['CORPS_HAUTEUR_DEPART']	= 45;
$ETAT_STOCK['CORPS_HAUTEUR_MAX']		= 205;

// PIEDS DE PAGE
$ETAT_STOCK['PIEDS_HAUTEUR_DEPART']	= 260;
$ETAT_STOCK['PIEDS_HAUTEUR_MAX']		= 12;

// ***************************************************
// TEXTES ENTRE CORPS ET PIEDS DE PAGE
$ETAT_STOCK['TEXTE_CORPS_PIEDS'][0]	= "";

// ***************************************************
// TEXTES DE PIEDS DE PAGE
global $PIED_DE_PAGE_GAUCHE_0;
global $PIED_DE_PAGE_GAUCHE_1;
global $PIED_DE_PAGE_DROIT_0;
global $PIED_DE_PAGE_DROIT_1;
$ETAT_STOCK['PIEDS_GAUCHE'][0]	= $PIED_DE_PAGE_GAUCHE_0;
$ETAT_STOCK['PIEDS_GAUCHE'][1]	= $PIED_DE_PAGE_GAUCHE_1;
$ETAT_STOCK['PIEDS_DROIT'][0]	= $PIED_DE_PAGE_DROIT_0;
$ETAT_STOCK['PIEDS_DROIT'][1]	= $PIED_DE_PAGE_DROIT_1;


//variable//type de champ(parametre)//libéllé//commentaire
// PARAMETRES MODIFIABLES
// FIN PARAMETRES MODIFIABLES
// CONFIGURATION PAR DEFAUT
// Portion de code recopiée dans la partie « paramètres modifiables » en cas de remise à 0 des paramètres.
/*
*/
// FIN CONFIGURATION PAR DEFAUT
// INFORMATIONS SUR L’AUTEUR
/* 
*/
?>
