<?php 
$CONFIGURATION=0;
$STAT_STANDARD['X'] = 1;
// CODE NON PARAMETRABLE
global $DOCUMENTS_IMG_LOGO;
$COURRIER_STANDARD['IMG_LOGO']	= $DOCUMENTS_IMG_LOGO;
// ***************************************************
// POSITION DES BLOCS
$COURRIER_STANDARD['MARGE_GAUCHE'] 	= 15;
$COURRIER_STANDARD['MARGE_HAUT']	= 15;

// PIEDS DE PAGE
$COURRIER_STANDARD['PIEDS_HAUTEUR_DEPART']	= 240;
$COURRIER_STANDARD['PIEDS_HAUTEUR_MAX']		= 32;

$COURRIER_STANDARD['FORMAT_PDF'][0] = 297; // hauteur
$COURRIER_STANDARD['FORMAT_PDF'][1] = 210; // largeur
// orientation
$COURRIER_STANDARD['ORIENTATION_PDF'] = 'L';
// ***************************************************
// LABELS
$COURRIER_STANDARD['LBL_NOS_REFS'][0] = 'nos ref.: ';
$COURRIER_STANDARD['LBL_NOS_REFS'][1] = ' client ';
$COURRIER_STANDARD['LBL_NOS_REFS'][2] = ', courrier ';
$COURRIER_STANDARD['LBL_VOS_REFS'][0] = '  vos ref.: ';
$COURRIER_STANDARD['LBL_OBJET'] = 'objet: ';
// ***************************************************
// TEXTES DE PIEDS DE PAGE
global $PIED_DE_PAGE_GAUCHE_0;
global $PIED_DE_PAGE_GAUCHE_1;
global $PIED_DE_PAGE_DROIT_0;
global $PIED_DE_PAGE_DROIT_1;
$COURRIER_STANDARD['PIEDS_GAUCHE'][0]	= $PIED_DE_PAGE_GAUCHE_0;
$COURRIER_STANDARD['PIEDS_GAUCHE'][1]	= $PIED_DE_PAGE_GAUCHE_1;
$COURRIER_STANDARD['PIEDS_DROIT'][0]		= $PIED_DE_PAGE_DROIT_0;
$COURRIER_STANDARD['PIEDS_DROIT'][1]		= $PIED_DE_PAGE_DROIT_1;
$COURRIER_STANDARD['PIEDS'][0]		= $COURRIER_STANDARD['PIEDS_GAUCHE'][0].'&nbsp;'.$COURRIER_STANDARD['PIEDS_DROIT'][0];
$COURRIER_STANDARD['PIEDS'][1]		= $COURRIER_STANDARD['PIEDS_GAUCHE'][1].'&nbsp;'.$COURRIER_STANDARD['PIEDS_DROIT'][1];

//variable//type de champ(parametre)//libéllé//commentaire
// PARAMETRES MODIFIABLES
$COURRIER_STANDARD['TEXTE_CORPS_PIEDS'][0]="jour j mois annee";//TXTE()// Format de la date//ligne n°1
$COURRIER_STANDARD['TEXTE_CORPS_PIEDS'][1]="TEST LIGNE 2";//TXTE()// Texte entre corps et pied de page//ligne n°2
$COURRIER_STANDARD['TEXTE_CORPS_PIEDS'][2]="";//TXTE()// Texte entre corps et pied de page//ligne n°3
// FIN PARAMETRES MODIFIABLES
?>