<?PHP 
$CONFIGURATION=1;

// CODE NON PARAMETRABLE
global $DOCUMENTS_IMG_LOGO;
$EXTRAIT_COMPTE['IMG_LOGO']	= $DOCUMENTS_IMG_LOGO;

$EXTRAIT_COMPTE['HAUTEUR_LINE_EXTRAIT']			= 5;
$EXTRAIT_COMPTE['HAUTEUR_LINE_TOTAUX_GENERAUX']		= 5;
$EXTRAIT_COMPTE['HAUTEUR_LINE_VIDE']				= 5;


$EXTRAIT_COMPTE['ENTETE_COL_DATE'] = "Date";
$EXTRAIT_COMPTE['ENTETE_COL_LIB'] = "Libellé";
$EXTRAIT_COMPTE['ENTETE_COL_DEBIT'] = "Dédit";
$EXTRAIT_COMPTE['ENTETE_COL_LT']  = "LT";
$EXTRAIT_COMPTE['ENTETE_COL_CREDIT'] 	= "Crédit";
$EXTRAIT_COMPTE['ENTETE_COL_SOLDE'] 	= "Solde";

$EXTRAIT_COMPTE['LARGEUR_COL_DATE'] = 20;
$EXTRAIT_COMPTE['LARGEUR_COL_LIB'] = 95;
$EXTRAIT_COMPTE['LARGEUR_COL_DEBIT'] = 20;
$EXTRAIT_COMPTE['LARGEUR_COL_LT'] = 10;
$EXTRAIT_COMPTE['LARGEUR_COL_CREDIT'] = 20;
$EXTRAIT_COMPTE['LARGEUR_COL_SOLDE'] = 20;

// ***************************************************
// POSITION DES BLOCS
$EXTRAIT_COMPTE['MARGE_GAUCHE'] = 15;
$EXTRAIT_COMPTE['MARGE_HAUT']		= 15;

// CORPS DU DOCUMENT
$EXTRAIT_COMPTE['CORPS_HAUTEUR_DEPART']	= 45;
$EXTRAIT_COMPTE['CORPS_HAUTEUR_MAX']		= 205;

// PIEDS DE PAGE
$EXTRAIT_COMPTE['PIEDS_HAUTEUR_DEPART']	= 260;
$EXTRAIT_COMPTE['PIEDS_HAUTEUR_MAX']		= 12;

// ***************************************************
// TEXTES ENTRE CORPS ET PIEDS DE PAGE
$ETAT_STOCK['TEXTE_CORPS_PIEDS'][0]	= "";

// ***************************************************
// TEXTES DE PIEDS DE PAGE
global $PIED_DE_PAGE_GAUCHE_0;
global $PIED_DE_PAGE_GAUCHE_1;
global $PIED_DE_PAGE_DROIT_0;
global $PIED_DE_PAGE_DROIT_1;
$EXTRAIT_COMPTE['PIEDS_GAUCHE'][0]	= $PIED_DE_PAGE_GAUCHE_0;
$EXTRAIT_COMPTE['PIEDS_GAUCHE'][1]	= $PIED_DE_PAGE_GAUCHE_1;
$EXTRAIT_COMPTE['PIEDS_DROIT'][0]	= $PIED_DE_PAGE_DROIT_0;
$EXTRAIT_COMPTE['PIEDS_DROIT'][1]	= $PIED_DE_PAGE_DROIT_1;



//variable//type de champ(parametre)//libéllé//commentaire
// PARAMETRES MODIFIABLES
// FIN PARAMETRES MODIFIABLES
// CONFIGURATION PAR DEFAUT
// Portion de code recopiée dans la partie « paramètres modifiables » en cas de remise à 0 des paramètres.
/*
*/
// FIN CONFIGURATION PAR DEFAUT
// INFORMATIONS SUR L’AUTEUR
/* 
*/
?>