<?PHP 
$CONFIGURATION=1;

// CODE NON PARAMETRABLE
global $DOCUMENTS_IMG_LOGO;
$STOCK_RNV['IMG_LOGO']	= $DOCUMENTS_IMG_LOGO;

$STOCK_RNV['HAUTEUR_LINE_ARTICLE']			= 5;
$STOCK_RNV['HAUTEUR_LINE_CATEGORIE']		= 5;
$STOCK_RNV['HAUTEUR_LINE_TOTAUX_CATEGORIE']	= 5;
$STOCK_RNV['HAUTEUR_LINE_TOTAUX_GENERAUX']	= 5;
$STOCK_RNV['HAUTEUR_LINE_VIDE']				= 5;

$STOCK_RNV['HAUTEUR_AFTER_LINE_ARTICLE']	= 0;
$STOCK_RNV['HAUTEUR_AFTER_LINE_CATEGORIE']	= 0;
$STOCK_RNV['HAUTEUR_AFTER_LINE_TOTAUX_CATEGORIE'] = 0;

$STOCK_RNV['LABEL_ARTICLES'] = "article(s)";
$STOCK_RNV['LABEL_PIECES'] = "pièce(s)";
$STOCK_RNV['LABEL_TOTAL_GENERAL'] = "TOTAL GENERAL: ";
$STOCK_RNV['ENTETE_COL_LIB'] = "Info. supp.";
$STOCK_RNV['ENTETE_COL_DEB'] = "Débit";
$STOCK_RNV['ENTETE_COL_CRE'] = "Crédit";

$STOCK_RNV['LARGEUR_COL_REF'] = 30;
$STOCK_RNV['LARGEUR_COL_LIB'] = 85;
$STOCK_RNV['LARGEUR_COL_QTE'] = 10;
$STOCK_RNV['LARGEUR_COL_PU'] = 20;
$STOCK_RNV['LARGEUR_COL_PT'] = 25;

// ***************************************************
// POSITION DES BLOCS
$STOCK_RNV['MARGE_GAUCHE'] 			= 15;
$STOCK_RNV['MARGE_HAUT']			= 15;

// CORPS DU DOCUMENT
$STOCK_RNV['CORPS_HAUTEUR_DEPART']	= 45;
$STOCK_RNV['CORPS_HAUTEUR_MAX']		= 205;

// PIEDS DE PAGE
$STOCK_RNV['PIEDS_HAUTEUR_DEPART']	= 260;
$STOCK_RNV['PIEDS_HAUTEUR_MAX']		= 12;

// ***************************************************
// TEXTES ENTRE CORPS ET PIEDS DE PAGE
$STOCK_RNV['TEXTE_CORPS_PIEDS'][0]	= "";

// ***************************************************
// TEXTES DE PIEDS DE PAGE
global $PIED_DE_PAGE_GAUCHE_0;
global $PIED_DE_PAGE_GAUCHE_1;
global $PIED_DE_PAGE_DROIT_0;
global $PIED_DE_PAGE_DROIT_1;
$STOCK_RNV['PIEDS_GAUCHE'][0]	= $PIED_DE_PAGE_GAUCHE_0;
$STOCK_RNV['PIEDS_GAUCHE'][1]	= $PIED_DE_PAGE_GAUCHE_1;
$STOCK_RNV['PIEDS_DROIT'][0]	= $PIED_DE_PAGE_DROIT_0;
$STOCK_RNV['PIEDS_DROIT'][1]	= $PIED_DE_PAGE_DROIT_1;



//variable//type de champ(parametre)//libéllé//commentaire
// PARAMETRES MODIFIABLES
// FIN PARAMETRES MODIFIABLES
// CONFIGURATION PAR DEFAUT
// Portion de code recopiée dans la partie « paramètres modifiables » en cas de remise à 0 des paramètres.
/*
*/
// FIN CONFIGURATION PAR DEFAUT
// INFORMATIONS SUR L’AUTEUR
/* 
*/
?>